import Account from './account.js';
import Company from './company.js';
import DataDict from './data-dict.js';
import Dept from './dept.js';
import File from './file.js';
import Folder from './folder.js';
import Log from './log.js';
import Notification from './notification.js';
import Path from './path.js';
import SavedFile from './saved-file.js';
import SavedFolder from './saved-folder.js';
import User from './user.js';

export const AccountModel = new Account();
export const CompanyModel = new Company();
export const DataDictModel = new DataDict();
export const DeptModel = new Dept();
export const FileModel = new File();
export const FolderModel = new Folder();
export const LogModel = new Log();
export const NotificationModel = new Notification();
export const PathModel = new Path();
export const SavedFileModel = new SavedFile();
export const SavedFolderModel = new SavedFolder();
export const UserModel = new User();
